# https://docs.travis-ci.com/user/languages/r
language: r
# dist: trusty # default is trusty, and with sudo false, only trusty.
# https://ropensci.org/blog/2016/07/12/travis-osx
# https://docs.travis-ci.com/user/ci-environment/

# required is slower to start but lets us install binary R packages more quickly
sudo: required
cache: packages

# duplicate what's in DESCRIPTION
r_binary_packages:
  - checkmate
  - covr
  - knitr
  - magrittr
  - rmarkdown
  - roxygen2
  - testthat
  - tinytex
  - xml2

# is this not automatic based on package DESCRIPTION?
r_packages:
  - icd.data
  - lintr
  - Rcpp
  - rticles

r:
  - devel
  - release
  - oldrel

cran: https://cloud.r-project.org

warnings_are_errors: true

env:
  global:
    - _R_CHECK_CRAN_INCOMING_=FALSE
    - _R_CHECK_CRAN_INCOMING_REMOTE_=FALSE
    - _R_CHECK_FORCE_SUGGESTS_=FALSE
    - LINTR_COMMENT_BOT=false
    - ICD_COVERAGE=false
    - OMP_NUM_THREADS=2
    - CFLAGS="-Og -Werror -Wall -Wextra -pedantic"
    - CXXFLAGS="-Og -Werror -Wall -Wextra -pedantic"

matrix:
  fast_finish: true
  include:
  - env: LINTR_COMMENT_BOT=true
  - env: ICD_COVERAGE=true ICD_TEST_DEPRECATED=true ICD_TEST_BUILD_DATA=true ICD_TEST_SLOW=true
  - env: ICD_TEST_ALL=false ICD_TEST_DEPRECATED=true ICD_TEST_BUILD_DATA=true ICD_TEST_SLOW=true
    r: release
  allow_failures:
  - env: ICD_COVERAGE=true ICD_TEST_DEPRECATED=true ICD_TEST_BUILD_DATA=true ICD_TEST_SLOW=true
  - r: oldrel

before_script:
 - rm .Rinstignore  # do install everything for testing
 - sed -i'' '/.*[Dd]ata.*/d' .Rbuildignore # do include data for testing
 - sed -i'' '/\.covrignore/d' .Rbuildignore
 - sed -i'' '/\.lintr/d' .Rbuildignore
 - Rscript -e "Rcpp::compileAttributes()" # make sure Rcpp generated code is updated, ideally this is not be checked in repo...

after_success:
 - if [ "$ICD_COVERAGE" = "true" ]; then
     Rscript -e "covr::codecov(quiet = FALSE)"; fi
 - if [ "$LINTR_COMMENT_BOT" = "true" ]; then
     Rscript -e "lintr::lint_package()"; fi

notifications:
  email:
    on_success: change
    on_failure: change
