# https://docs.travis-ci.com/user/languages/r
language: r
# https://ropensci.org/blog/2016/07/12/travis-osx
# https://docs.travis-ci.com/user/ci-environment/

fortran: false

os:
  - linux
  - osx

dist:
  - xenial

sudo: false
cache:
  - packages
  - ccache

r_packages:
  - covr

cran: https://cloud.r-project.org

warnings_are_errors: true

# try to speed up compilation time
before_install:
  - if [[ "$TRAVIS_R_VERSION_STRING" = 'devel' ]]; then
      mkdir ~/.R ;
      echo 'CC=clang' > ~/.R/Makevars ;
      echo 'CXX=clang++' >> ~/.R/Makevars ;
      echo 'CXX11=clang++' >> ~/.R/Makevars ;
      echo 'CFLAGS=-O0' >> ~/.R/Makevars ;
      echo 'CXXFLAGS=-O0' >> ~/.R/Makevars ;
      echo 'CXX11FLAGS=-O0' >> ~/.R/Makevars ;
      fi

env:
  global:
    - _R_CHECK_CRAN_INCOMING_=FALSE
    - _R_CHECK_CRAN_INCOMING_REMOTE_=FALSE
    - _R_CHECK_FORCE_SUGGESTS_=FALSE
    - ICD_COVERAGE=false
    - ICD_MINI_BENCH=false
    - ICD_DATA_VERBOSE=true
    - ICD_DATA_OFFLINE=true
    - ICD_DATA_INTERACT=false
#    env: LINTR_COMMENT_BOT=true

matrix:
  fast_finish: true
  include:
  - r: devel
    os: linux
    dist: xenial
  - r: devel
    os: osx
    osx_image: xcode10.2
  - r: devel
    os: osx
    # as of April 2019, default osx image is 9.4
  - r: release
    os: linux
    dist: precise
  - r: release
    os: osx
    latex: false
    r_build_args: --no-build-vignettes --no-manual --resave-data=no
    r_check_args: --no-build-vignettes --no-vignettes --ignore-vignettes --no-codoc --no-manual
    env:
    - ICD_MINI_BENCH=true
  - r: oldrel
    os: linux
    dist: precise
    latex: false
    r_build_args: --no-build-vignettes --no-manual --resave-data=no
    r_check_args: --no-build-vignettes --no-vignettes --ignore-vignettes --no-codoc --no-manual
  - r: release
    os: linux
    dist: xenial
    latex: false
    r_build_args: --no-build-vignettes --no-manual --resave-data=no
    r_check_args: --no-build-vignettes --no-vignettes --ignore-vignettes --no-codoc --no-manual --use-valgrind
    env:
    - ICD_COVERAGE=true
    - ICD_TEST_SLOW=true
  allow_failures:
  - r: oldrel
    latex: false
    r_build_args: --no-build-vignettes --no-manual --resave-data=no
    r_check_args: --no-build-vignettes --no-vignettes --ignore-vignettes --no-codoc --no-manual
  - r: release
    os: linux
    dist: xenial
    latex: false
    r_build_args: --no-build-vignettes --no-manual --resave-data=no
    r_check_args: --no-build-vignettes --no-vignettes --ignore-vignettes --no-codoc --no-manual --use-valgrind
    env:
    - ICD_COVERAGE=true
    - ICD_TEST_SLOW=true

before_script:
 - rm .Rinstignore  # do install everything for testing
 - sed -i'' '/.*[Dd]ata.*/d' .Rbuildignore # do include data for testing
# - sed -i'' '/\.covrignore/d' .Rbuildignore
# - sed -i'' '/\.lintr/d' .Rbuildignore
 - sed -i'' '/\benchmark/d' .Rbuildignore
 - Rscript -e "Rcpp::compileAttributes()" # make sure Rcpp generated code is updated, ideally this is not be checked in repo...

after_success:
 - if [ "ICD_MINI_BENCH" = "true" ]; then
     cd benchmarks/icd-JSS3447-replication;
     make bench3; make replmat;
   fi
 - if [ "$ICD_COVERAGE" = "true" ]; then
     Rscript -e "covr::codecov(quiet = FALSE)"; fi
# - if [ "$LINTR_COMMENT_BOT" = "true" ]; then
#     Rscript -e "lintr::lint_package()"; fi

notifications:
  email:
    on_success: change
    on_failure: change
