# https://docs.travis-ci.com/user/languages/r
language: r
# https://ropensci.org/blog/2016/07/12/travis-osx
# https://docs.travis-ci.com/user/ci-environment/

sudo: false
cache: packages

r_packages:
  - covr
# following from DESCRIPTION so travis can cache
  - checkmate
  - magrittr
  - Rcpp
  - knitr
  - roxygen2
  - rmarkdown
  - rticles
  - testthat
  - tinytex
  - xml2

r_github_packages:
  - jimhester/lintr
  # for testing against icd.data which is not yet updated in CRAN
  - jackwasey/icd.data@WHO

cran: https://cloud.r-project.org

warnings_are_errors: true

# try to speed up compilation time
before_install:
  - if [[ "$TRAVIS_R_VERSION_STRING" = 'devel' ]]; then
      mkdir ~/.R ;
      echo 'CC=clang' > ~/.R/Makevars ;
      echo 'CXX=clang++' >> ~/.R/Makevars ;
      echo 'CXX11=clang++' >> ~/.R/Makevars ;
      echo 'CFLAGS=-O0 -march=native' >> ~/.R/Makevars ;
      echo 'CXXFLAGS=-O0 -march=native' >> ~/.R/Makevars ;
      echo 'CXX11FLAGS=-O0 -march=native' >> ~/.R/Makevars ;
      fi

env:
  global:
    - _R_CHECK_CRAN_INCOMING_=FALSE
    - _R_CHECK_CRAN_INCOMING_REMOTE_=FALSE
    - _R_CHECK_FORCE_SUGGESTS_=FALSE
    - LINTR_COMMENT_BOT=false
    - ICD_COVERAGE=false
    - ICD_TEST_DEPRECATED=false
    - ICD_TEST_BUILD_DATA=false
    - ICD_TEST_SLOW=false

matrix:
  fast_finish: true
  include:
  - r: devel
    env: LINTR_COMMENT_BOT=true
  - r: release
  - r: oldrel
    r_build_args: --no-build-vignettes --no-manual --resave-data=no
    r_check_args: --no-build-vignettes --no-vignettes --ignore-vignettes --no-codoc --no-manual
  - r: release
    r_build_args: --no-build-vignettes --no-manual --resave-data=no
    r_check_args: --no-build-vignettes --no-vignettes --ignore-vignettes --no-codoc --no-manual
    env:
    - ICD_COVERAGE=true
    - ICD_TEST_DEPRECATED=true
    - ICD_TEST_BUILD_DATA=true
    - ICD_TEST_SLOW=true
  allow_failures:
  # temporarily allow failure for lintr run on travis as a dependency of lintr fails to install.
  - r: oldrel
    r_build_args: --no-build-vignettes --no-manual --resave-data=no
    r_check_args: --no-build-vignettes --no-vignettes --ignore-vignettes --no-codoc --no-manual
  - r: release
    r_build_args: --no-build-vignettes --no-manual --resave-data=no
    r_check_args: --no-build-vignettes --no-vignettes --ignore-vignettes --no-codoc --no-manual
    env:
    - ICD_COVERAGE=true
    - ICD_TEST_DEPRECATED=true
    - ICD_TEST_BUILD_DATA=true
    - ICD_TEST_SLOW=true

before_script:
 - rm .Rinstignore  # do install everything for testing
 - sed -i'' '/.*[Dd]ata.*/d' .Rbuildignore # do include data for testing
 - sed -i'' '/\.covrignore/d' .Rbuildignore
 - sed -i'' '/\.lintr/d' .Rbuildignore
 - sed -i'' '/\benchmark/d' .Rbuildignore
 - Rscript -e "Rcpp::compileAttributes()" # make sure Rcpp generated code is updated, ideally this is not be checked in repo...

after_success:
 - if [ "$ICD_COVERAGE" = "true" ]; then
     cd benchmarks/icd-JSS3447-replication;
     make bench3; make replmat;
   fi
 - if [ "$ICD_COVERAGE" = "true" ]; then
     Rscript -e "covr::codecov(quiet = FALSE)"; fi
 - if [ "$LINTR_COMMENT_BOT" = "true" ]; then
     Rscript -e "lintr::lint_package()"; fi

notifications:
  email:
    on_success: change
    on_failure: change
