# https://docs.travis-ci.com/user/languages/r
language: r
# dist: trusty
# precise vs trusty as of Jan 2017. Use old environment for testing old compilers, R?
# trusty will only work with sudo: true for now
# https://ropensci.org/blog/2016/07/12/travis-osx
# https://docs.travis-ci.com/user/ci-environment/

sudo: false
cache: packages

# duplicate what's in DESCRIPTION
r_binary_packages:
  - checkmate
  - magrittr
  - Rcpp
  - stringr
  - testthat

r_packages:
  - knitr
  - roxygen2
  - rmarkdown

r_github_packages:
  - jimhester/covr
  - jimhester/lintr

r:
  - devel
  - release
  - oldrel

cran: https://cloud.r-project.org

warnings_are_errors: true

env:
  global:
    - R_CHECK_CRAN_INCOMING_=FALSE _R_CHECK_FORCE_SUGGESTS_=FALSE
    - LINTR_COMMENT_BOT=false
    - ICD_COVERAGE=false
  matrix:
    - OMP_NUM_THREADS=1 CFLAGS="-Og -Werror -Wall -Wextra -pedantic" CXXFLAGS="-Og -Werror -Wall -Wextra -pedantic"
    - OMP_NUM_THREADS=2 CFLAGS="-O3 -march=native" CXXFLAGS="-O3 -march=native"

matrix:
  fast_finish: true
  include:
  - env: LINTR_COMMENT_BOT=true
  - env: ICD_COVERAGE=true ICD_TEST_DEPRECATED=true ICD_TEST_BUILD_DATA=true ICD_TEST_SLOW=true
  allow_failures:
  - r: oldrel
  - env: ICD_COVERAGE=true ICD_TEST_DEPRECATED=true ICD_TEST_BUILD_DATA=true ICD_TEST_SLOW=true

before_script:
 - ls -aR
 - rm .Rinstignore  # do install everything for testing
 - sed -i'' '/.*[Dd]ata.*/d' .Rbuildignore # do include data for testing
 - sed -i'' '/\.covrignore/d' .Rbuildignore
 - sed -i'' '/\.lintr/d' .Rbuildignore
 - Rscript -e "Rcpp::compileAttributes()" # make sure Rcpp generated code is updated, ideally this is not be checked in repo...

after_success:
 - ls -aR
 - cat ./icd.Rcheck/tests/test-all.Rout
 - if [ "$ICD_COVERAGE" = "true" ]; then
     Rscript -e "covr::codecov(quiet = FALSE)"; fi
 - Rscript -e "lintr::lint_package()"

notifications:
  email:
    on_success: change
    on_failure: change
