# DO NOT CHANGE the "init" and "install" sections below
#
# See for examples: https://github.com/krlmlr/r-appveyor/blob/master/appveyor.yml#L20
# and
# https://github.com/krlmlr/r-appveyor
# for many environment variables to configure

# Download script file from GitHub
init:
    ps: |
        GetDate
        $ErrorActionPreference = "Stop"

    install:
        ps: |
            Import-Module '.\scripts\appveyor-tool.ps1'
            Bootstrap

            # temporarily disable cache if error? can use APPVEYOR_CACHE_SKIP_RESTORE: true
        cache:
            - C:\RLibrary

        platform:
            - x86
            - x64

        before_build:
            - ls -aR
            - tools/dump-env.sh
            - rm .Rinstignore  # do install everything for testing
            - sed -i'' -e '/.*[Dd]ata.*/d' .Rbuildignore # do include data for testing, some data not in github though
              #- Rscript -e "install.packages(c('remotes', 'Rcpp', 'knitr', 'nhds'), repos = 'https://cloud.r-project.org/'); Rcpp::compileAttributes()"

        build_script:
            - travis-tool.sh install_deps

        environment:
            # APPVEYOR_CACHE_SKIP_RESTORE: true
            WARNINGS_ARE_ERRORS: 0
            _R_CHECK_EXIT_ON_FIRST_ERROR_: true
            USE_RTOOLS: true
            R_BUILD_ARGS: "--no-manual --no-build-vignettes"
            R_CHECK_ARGS: "--no-manual --ignore-vignettes --no-build-vignettes"
            NOT_CRAN: true
            ICD_DATA_VERBOSE: true
            ICD_DATA_OFFLINE: true
            ICD_DATA_INTERACT: false
            KEEP_VIGNETTES: ""
            # by default, don't set environment, to be more like CRAN?
            #  ICD_DATA_ABSENT_ACTION: 'message'
            #  R_REMOTES_STANDALONE: Set this to true if builds are failing due to the inability to update infrastructure packages such as curl, git2r and rlang. Read more in the docs for the remotes package.
            matrix:
                - R_VERSION: patched
                  MINI_BENCH: "no"
                - R_VERSION: release
                  MINI_BENCH: "yes"
                - R_VERSION: devel

                  matrix:
                      fast_finish: false
                      allow_failures:
                          - platform: x64
                            MINI_BENCH: "yes"
                            #  exclude:
                            #    - platform: x86
                            #      MINI_BENCH: "yes"

                            test_script:
                                - travis-tool.sh run_tests

                            on_failure:
                                - 7z a failure.zip *.Rcheck\*
                                - appveyor PushArtifact failure.zip

                            after_build:
                                - pwd
                                - IF NOT "%MINI_BENCH%"=="" cd benchmarks/icd-JSS3447-replication
                                - IF NOT "%MINI_BENCH%"=="" make bench3
                                  #  - IF NOT "%MINI_BENCH%"=="" make replmat # needs to call Rscript on appveyor path.
                                - IF NOT "%MINI_BENCH%"=="" cd ../..

                            artifacts:
                                - path: '*.Rcheck\**\*.log'
                                  name: Logs

                                - path: '*.Rcheck\**\*.out'
                                  name: Logs

                                - path: '*.Rcheck\**\*.fail'
                                  name: Logs

                                - path: '*.Rcheck\**\*.Rout'
                                  name: Logs

                                - path: '\*_*.tar.gz'
                                  name: Bits

                                - path: '\*_*.zip'
                                  name: Bits

                                  notifications:
                                      - provider: Email
                                        to:
                                            - appveyor@jackwasey.com
                                              #   subject: 'r-appveyor build {{status}}'                  # optional
                                              #   message: "https://ci.appveyor.com/project/krlmlr/r-appveyor"    # optional
                                        on_build_success: false
                                        on_build_failure: true
                                        on_build_status_changed: true
